CREATE TABLE web_users (
    customer_id VARCHAR2(40 CHAR) PRIMARY KEY REFERENCES demo_wallets(customer_id),
    password_hash VARCHAR2(100 CHAR) NOT NULL,
    role_name VARCHAR2(16 CHAR) NOT NULL CHECK (role_name IN ('CLIENTE','EMPLEADO','ADMIN')),
    first_name VARCHAR2(80 CHAR) NOT NULL,
    last_name VARCHAR2(120 CHAR) NOT NULL,
    address VARCHAR2(240 CHAR) NOT NULL,
    phone VARCHAR2(20 CHAR) NOT NULL,
    email VARCHAR2(254 CHAR) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);
GRANT SELECT, INSERT, UPDATE, DELETE ON web_users TO CINE_APP;
